import Foundation

/// Translations (fr / en), key → string; `en` is the fallback. `%@` marks
/// the arguments of `AppSettings.t(_:_:)`.
enum Strings {
    static let table: [String: [String: String]] = [
        "fr": [
            // Welcome
            "welcome_title": "Bienvenue",
            "welcome_subtitle": "Le client macOS de vibe serve : tableau des tâches, approbations, activité en direct.",
            "welcome_open": "Ouvrir un projet…",
            "welcome_connect": "Se connecter à un serveur lancé",
            "welcome_drop_hint": "Ou déposez un dossier de projet sur cette fenêtre.",
            "welcome_recent": "Projets récents",
            "welcome_no_recent": "Aucun projet récent",
            "welcome_no_recent_desc": "Les projets ouverts apparaîtront ici.",
            "welcome_forget": "Retirer de la liste",
            "remote_help": "Pour un `vibe serve` lancé dans un terminal : collez son URL (ou la ligne « open …#token=… ») et son jeton. Le jeton est gardé dans le Trousseau.",
            "remote_url": "URL",
            "remote_token": "Jeton",
            "invalid_url": "URL invalide :",
            "connect": "Se connecter",

            // Menus
            "menu_open_project": "Ouvrir un projet…",
            "menu_welcome": "Fenêtre de bienvenue",
            "menu_task": "Tâche",
            "menubar_summary": "%@ en cours · %@ en attente d'approbation",
            "menubar_no_project": "Aucun projet ouvert",
            "quit": "Quitter Vibe Factory",
            "open": "Ouvrir",

            // Connection
            "starting_server": "Démarrage de vibe serve…",
            "server_failed": "Impossible de joindre le serveur",
            "retry": "Réessayer",
            "open_settings": "Réglages…",
            "connected": "Connecté",
            "no_project": "Aucun projet pour cette fenêtre",

            // Sidebar and board
            "sidebar_tasks": "Tâches",
            "sidebar_project": "Projet",
            "sidebar_activity": "Activité",
            "sidebar_history": "Historique",
            "sidebar_evaluations": "Évaluations",
            "status_backlog": "À faire",
            "status_planning": "Planification",
            "status_building": "Construction",
            "status_review": "Revue",
            "status_ready": "Prête",
            "status_done": "Terminée",
            "status_failed": "Échouée",
            "status_cancelled": "Annulée",
            "status_other": "Autre",
            "no_tasks": "Aucune tâche",
            "no_tasks_desc": "Rien dans cette colonne pour l'instant.",
            "awaiting": "attend : %@",
            "select_task": "Aucune tâche sélectionnée",
            "select_task_desc": "Choisissez une tâche, ou créez-en une avec ⌘N.",
            "history_title": "Historique",
            "history_soon": "L'historique des tâches terminées arrive avec la prise en charge côté serveur (/api/history).",
            "activity_title": "Activité",
            "activity_soon": "Sélectionnez une tâche pour suivre son activité. Le flux global de tout le projet arrive avec /api/stream.",

            // Actions
            "action_new_task": "Nouvelle tâche",
            "action_run": "Lancer",
            "action_resume": "Reprendre",
            "action_cancel": "Annuler l'exécution",
            "action_approve": "Approuver",
            "action_reject": "Rejeter",
            "cancel": "Annuler",
            "create": "Créer",
            "choose": "Choisir…",
            "refresh": "Rafraîchir",
            "task_title": "Titre",
            "task_description": "Description (optionnelle)",

            // Detail
            "tab_overview": "Vue d'ensemble",
            "tab_activity": "Activité",
            "tab_changes": "Modifications",
            "tab_spec": "Spécification",
            "tab_plan": "Plan",
            "tab_qa": "Revue QA",
            "qa_round": "Tour",
            "validations": "Validations",
            "parallel": "en parallèle",
            "not_run": "Jamais lancée.",
            "no_spec": "Pas de spécification (les profils rapides s'en passent).",
            "no_plan": "Pas encore de plan.",
            "no_qa": "Pas encore de revue QA.",
            "no_activity": "Pas encore d'activité.",
            "no_changes": "Aucune modification dans l'espace de travail.",
            "loading": "Chargement…",
            "budget_tokens": "Jetons",
            "budget_time": "Temps actif",
            "approval_waiting": "En attente de votre approbation : %@",
            "approval_help": "Approuvez pour continuer, ou rejetez avec une raison que les agents reprendront.",
            "approve_title": "Approuver : %@",
            "approve_help": "Commentaire optionnel, conservé avec la décision.",
            "reject_title": "Rejeter : %@",
            "reject_help": "La raison est obligatoire : les agents refont leur travail à partir d'elle.",

            // Events
            "ev_run_started": "exécution démarrée",
            "ev_started": "démarre",
            "ev_finished": "a fini",
            "ev_failed": "a échoué",
            "ev_conflicts": "conflits dans",
            "ev_merged": "fusionné",
            "ev_wrote": "a écrit",
            "ev_approval_needed": "approbation requise :",
            "ev_approved": "approuvé",
            "ev_rejected": "rejeté",
            "ev_retrying": "nouvel essai",
            "ev_run_finished": "exécution terminée",

            // Notifications
            "notify_approval": "Approbation requise : %@",
            "notify_paused": "L'exécution est en pause.",
            "notify_finished": "Exécution terminée : %@",

            // Evaluations
            "evals_none": "Aucune évaluation",
            "evals_none_desc": "Aucun summary.json sous le dossier des évaluations.",
            "evals_disabled": "Choisissez un dossier d'évaluations dans les Réglages (vibe serve --evals).",
            "evals_disabled_title": "Évaluations désactivées",
            "evals_select": "Sélectionnez une suite",
            "evals_case": "Cas",
            "evals_provider": "Fournisseur",
            "evals_model": "Modèle",
            "evals_success": "Réussite",
            "evals_mean_time": "Temps moyen",
            "evals_median_time": "Temps médian",
            "evals_tokens": "Jetons moyens",

            // Settings
            "settings_title": "Réglages…",
            "settings_vibe": "Serveur",
            "settings_vibe_path": "Exécutable vibe",
            "settings_vibe_found": "Utilisé : %@",
            "settings_vibe_missing": "Introuvable : installez vibe (cargo install) ou choisissez l'exécutable.",
            "settings_evals": "Dossier des évaluations",
            "settings_restart_hint": "Pris en compte à la prochaine ouverture d'un projet.",
            "settings_appearance": "Apparence",
            "appearance_system": "Système",
            "appearance_light": "Clair",
            "appearance_dark": "Sombre",
            "settings_language": "Langue",
            "language_system": "Système",
            "settings_notifications": "Notifications",
            "settings_notifications_toggle": "Prévenir des approbations, pauses et fins d'exécution",

            "server_exited": "vibe serve s'est arrêté (statut %@).",
            "remove": "Retirer",
            "add": "Ajouter",
            "env_name": "Variable",
            "env_value": "Valeur",
            "settings_env": "Variables d'environnement du serveur",
            "settings_env_help": "Données à vibe serve (par ex. les clés nommées par api_key_env) : une app lancée depuis le Finder ne voit pas les variables exportées par le shell. Les valeurs sont gardées dans le Trousseau.",

            // Misc
            "ok": "OK",
            "error_title": "Erreur",
        ],
        "en": [
            "welcome_title": "Welcome",
            "welcome_subtitle": "The macOS client of vibe serve: task board, approvals, live activity.",
            "welcome_open": "Open a project…",
            "welcome_connect": "Connect to a running server",
            "welcome_drop_hint": "Or drop a project folder on this window.",
            "welcome_recent": "Recent projects",
            "welcome_no_recent": "No recent project",
            "welcome_no_recent_desc": "Projects you open appear here.",
            "welcome_forget": "Remove from the list",
            "remote_help": "For a `vibe serve` started in a terminal: paste its URL (or its “open …#token=…” line) and its token. The token is kept in the Keychain.",
            "remote_url": "URL",
            "remote_token": "Token",
            "invalid_url": "Invalid URL:",
            "connect": "Connect",

            "menu_open_project": "Open Project…",
            "menu_welcome": "Welcome Window",
            "menu_task": "Task",
            "menubar_summary": "%@ running · %@ awaiting approval",
            "menubar_no_project": "No open project",
            "quit": "Quit Vibe Factory",
            "open": "Open",

            "starting_server": "Starting vibe serve…",
            "server_failed": "Cannot reach the server",
            "retry": "Retry",
            "open_settings": "Settings…",
            "connected": "Connected",
            "no_project": "No project for this window",

            "sidebar_tasks": "Tasks",
            "sidebar_project": "Project",
            "sidebar_activity": "Activity",
            "sidebar_history": "History",
            "sidebar_evaluations": "Evaluations",
            "status_backlog": "Backlog",
            "status_planning": "Planning",
            "status_building": "Building",
            "status_review": "Review",
            "status_ready": "Ready",
            "status_done": "Done",
            "status_failed": "Failed",
            "status_cancelled": "Cancelled",
            "status_other": "Other",
            "no_tasks": "No tasks",
            "no_tasks_desc": "Nothing in this column yet.",
            "awaiting": "awaiting: %@",
            "select_task": "No task selected",
            "select_task_desc": "Pick a task, or create one with ⌘N.",
            "history_title": "History",
            "history_soon": "The history of finished tasks arrives with the server support (/api/history).",
            "activity_title": "Activity",
            "activity_soon": "Select a task to follow its activity. The project-wide feed arrives with /api/stream.",

            "action_new_task": "New Task",
            "action_run": "Run",
            "action_resume": "Resume",
            "action_cancel": "Cancel Run",
            "action_approve": "Approve",
            "action_reject": "Reject",
            "cancel": "Cancel",
            "create": "Create",
            "choose": "Choose…",
            "refresh": "Refresh",
            "task_title": "Title",
            "task_description": "Description (optional)",

            "tab_overview": "Overview",
            "tab_activity": "Activity",
            "tab_changes": "Changes",
            "tab_spec": "Specification",
            "tab_plan": "Plan",
            "tab_qa": "QA review",
            "qa_round": "Round",
            "validations": "Validations",
            "parallel": "parallel",
            "not_run": "Not run yet.",
            "no_spec": "No specification (quick profiles skip it).",
            "no_plan": "No plan yet.",
            "no_qa": "No QA report yet.",
            "no_activity": "No activity yet.",
            "no_changes": "No change in the workspace.",
            "loading": "Loading…",
            "budget_tokens": "Tokens",
            "budget_time": "Active time",
            "approval_waiting": "Waiting for your approval: %@",
            "approval_help": "Approve to continue, or reject with a reason the agents will work from.",
            "approve_title": "Approve: %@",
            "approve_help": "Optional comment, kept with the decision.",
            "reject_title": "Reject: %@",
            "reject_help": "The reason is required: the agents redo their work from it.",

            "ev_run_started": "run started",
            "ev_started": "started",
            "ev_finished": "finished",
            "ev_failed": "failed",
            "ev_conflicts": "conflicts in",
            "ev_merged": "merged",
            "ev_wrote": "wrote the",
            "ev_approval_needed": "approval needed:",
            "ev_approved": "approved",
            "ev_rejected": "rejected",
            "ev_retrying": "retrying",
            "ev_run_finished": "run finished",

            "notify_approval": "Approval needed: %@",
            "notify_paused": "The run is paused.",
            "notify_finished": "Run finished: %@",

            "evals_none": "No evaluations",
            "evals_none_desc": "No summary.json under the evaluations directory.",
            "evals_disabled": "Choose an evaluations directory in Settings (vibe serve --evals).",
            "evals_disabled_title": "Evaluations are off",
            "evals_select": "Select a suite",
            "evals_case": "Case",
            "evals_provider": "Provider",
            "evals_model": "Model",
            "evals_success": "Success",
            "evals_mean_time": "Mean time",
            "evals_median_time": "Median time",
            "evals_tokens": "Mean tokens",

            "settings_title": "Settings…",
            "settings_vibe": "Server",
            "settings_vibe_path": "vibe executable",
            "settings_vibe_found": "Using: %@",
            "settings_vibe_missing": "Not found: install vibe (cargo install) or choose the executable.",
            "settings_evals": "Evaluations directory",
            "settings_restart_hint": "Applies the next time a project is opened.",
            "settings_appearance": "Appearance",
            "appearance_system": "System",
            "appearance_light": "Light",
            "appearance_dark": "Dark",
            "settings_language": "Language",
            "language_system": "System",
            "settings_notifications": "Notifications",
            "settings_notifications_toggle": "Notify on approvals, pauses and finished runs",

            "server_exited": "vibe serve stopped (status %@).",
            "remove": "Remove",
            "add": "Add",
            "env_name": "Variable",
            "env_value": "Value",
            "settings_env": "Server environment variables",
            "settings_env_help": "Given to vibe serve (for example the keys named by api_key_env): an app started from the Finder does not see variables exported by the shell. Values are kept in the Keychain.",

            "ok": "OK",
            "error_title": "Error",
        ],
    ]
}
